### ISSUE TITLE
Reliable Data from Credible Sources 3

### ISSUE THREAD

**Issue by michael2750** [pwestdk/Messaging#2]
Når i udtaler jer om f.eks hvordan messaging fungere burde i have en form for ressource til at opbakke det. Det kan være et link fra jeres “furthere reading” sektion, eller et billed fra en benchmark. Ligesom i har gjort i den sidste del af “Outlook”, hvor i relatere til RabbitMQ.

**Comment by ehn94** [comment]
Vi har gjort brug af flere kilder, både om messaging queues og andre teknologier. Derudover har vi indsat kilder undervejs i teksten, når vi gør brug af dem.
