### ISSUE TITLE
Design Constraints and Assumptions 8

### ISSUE THREAD

**Issue by michael2750** [pwestdk/Messaging#3]
Meget godt. I giver et alternativ til messaging og begrunder for hvilken metode der er mest brugbar. (Dette er vi ikke helt sikker på) Umiddelbart vil vi ikke sige at REST kun er synchronous. REST tager imod en HTTP package, men det vel ikke her der bliver bestemt hvorvidt den er asynchronous eller synchronous. Ville mere sige det er op til den service som sender requesten, om den vil vente på et response, eller lave et callback på en ny thread. Her har vi læst lidt om det: https://stackoverflow.com/questions/16060372/rest-web-services-synchronous-or-asynchrous

**Comment by ehn94** [comment]
Vi har valgt ikke at opstille forsøg eller gøre brug af kalkuleringer, da vi har fokuseret mere på en teoretisk redegørelse for messaging queues, samt analyse ud fra denne teori.
Vi har flyttet vores fokus fra sammenligningen med REST til udelukkende fokus på messaging queues og redegørelse for denne.
Derudover har vi rettet vores fejlagtige udtalelse omkring REST.
