### ISSUE TITLE
Theoretical Explanations 5

### ISSUE THREAD

**Issue by michael2750** [pwestdk/Messaging#4]
Research delen er god. Der mangler noget analyse, det kunne for eksempel være hvor hurtigt man kan transportere data igennem messaging i forhold til REST.
Eller når i snakker blocking/non-blocking, hvor mange requests kan servicen håndtere under disse omstændigheder.

**Comment by ehn94** [comment]
Vi har valgt ikke at opstille forsøg eller gøre brug af kalkuleringer, da vi har fokuseret mere på en teoretisk redegørelse for messaging queues, samt analyse ud fra denne teori.
Vi har flyttet vores fokus fra sammenligningen med REST til udelukkende fokus på messaging queues og redegørelse for denne.
