### ISSUE TITLE
Design Criteria, Sample Calculations and Simulations 7

### ISSUE THREAD

**Issue by michael2750** [pwestdk/Messaging#5]
Relatere måske lidt til noget analyse, at man kan stille en kalkulering op (f.eks billede af en benchmark), men ellers kan vi ikke se hvordan man skulle simulere/kalkulere kobling i en service.

**Comment by ehn94** [comment]
Vi har valgt ikke at opstille forsøg eller gøre brug af kalkuleringer, da vi har fokuseret mere på en teoretisk redegørelse for messaging queues, samt analyse ud fra denne teori.
